services:
  nginx:
    build:
      context: ./docker/development/nginx
    volumes:
      - ./docker/development/nginx:/etc/nginx/conf.d:ro,delegated
      - ./public:/var/www/public:ro,delegated
    restart: on-failure
    ports:
      - "127.0.0.1:8080:80"

  backend:
    build:
      context: ./docker/development/backend
    command: docker-php-entrypoint php-fpm
    volumes:
      - ./:/var/www:delegated
    restart: on-failure

  keydb:
    build:
      context: ./docker/development/keydb
    restart: on-failure
    volumes:
      - ./docker/host/dir:/data
    ports:
      - "127.0.0.1:6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      REDIS_HOSTS: keydb
      REDIS_HOST: keydb
      REDIS_PORT: keydb:6379
      #REDIS_PASSWORD: secret
      #HTTP_USER: root
      #HTTP_PASSWORD: root
    ports:
      - "8081:8081"

  #keydb-by-indus:
  #  image: vsaps/keydb_jsonsearch:latest
  #  restart: always
  #  ports:
  #    - "127.0.0.1:6378:6379"