monolog:
    channels: ['embedding', 'vectorizer']
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            #max_files: 10
            #max_file_size: 5242880 #5MB
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]

        embedding:
            level:    debug
            type:     stream
            path:     '%kernel.logs_dir%/embedding_search.log'
            channels: [embedding]

        vectorizer:
            level:    debug
            type:     stream
            path:     '%kernel.logs_dir%/vectorizer.log'
            channels: [vectorizer]
