# Pages
gpt_request_page:
    path: /
    controller: App\Controller\AppController::gptRequestPage
    methods: GET|HEAD

gpt_assistant_page:
    path: /assistant
    controller: App\Controller\AppController::gptAssistantPage
    methods: GET|HEAD

gpt_search_page:
    path: /search
    controller: App\Controller\AppController::gptSearchPage
    methods: GET|HEAD

gpt_summarize_page:
    path: /summarize
    controller: App\Controller\AppController::gptSummarizePage
    methods: GET|HEAD

gpt_request_history_rows:
    path: /gpt/request/history
    controller: App\Controller\GptRequestHistoryController::index
    methods: GET|HEAD

gpt_request_history_row:
    path: /gpt/request/history/{gptRequestHistory}
    controller: App\Controller\GptRequestHistoryController::show
    methods: GET|HEAD

knowledgebase_data_upload_page:
    path: /knowledgebase/data/upload
    controller: App\Controller\DataUploadController::index
    methods: GET|HEAD

knowledgebase_articles:
    path: /knowledgebase/articles
    controller: App\Controller\ArticleController::index
    methods: GET|HEAD

knowledgebase_article:
    path: /knowledgebase/articles/{article}
    controller: App\Controller\ArticleController::show
    methods: GET|HEAD

knowledgebase_article_paragraph:
    path: /knowledgebase/articles/{article}/paragraphs/{articleParagraph}
    controller: App\Controller\ArticleParagraphController::show
    methods: GET|HEAD

knowledgebase_templates:
    path: /knowledgebase/templates
    controller: App\Controller\TemplateController::index
    methods: GET|HEAD

knowledgebase_template:
    path: /knowledgebase/templates/{template}
    controller: App\Controller\TemplateController::show
    methods: GET|HEAD

# Actions
gpt_request:
    path: /gpt/request
    controller: App\Controller\AppController::request
    methods: POST

gpt_assistant_list:
    path: /gpt/assistant/list
    controller: App\Controller\AppController::assistantList
    methods: POST

gpt_assistant_request:
    path: /gpt/assistant/request
    controller: App\Controller\AppController::assistantRequest
    methods: POST

gpt_vectorize:
    path: /gpt/vectorize
    controller: App\Controller\AppController::vectorize
    methods: POST

gpt_search:
    path: /gpt/search
    controller: App\Controller\AppController::search
    methods: POST

gpt_summarize:
    path: /gpt/summarize
    controller: App\Controller\AppController::summarize
    methods: POST

knowledgebase_data_upload:
    path: /knowledgebase/data/upload
    controller: App\Controller\DataUploadController::upload
    methods: POST

knowledgebase_categories_upload:
    path: /knowledgebase/categories/upload
    controller: App\Controller\KnowledgebaseCategoryController::upload
    methods: POST

knowledgebase_sections_upload:
    path: /knowledgebase/sections/upload
    controller: App\Controller\KnowledgebaseSectionController::upload
    methods: POST

# Messages
message_store:
    path: /messages
    controller: App\Controller\MessageController::store
    methods: POST

messages_upload:
    path: /messages/upload
    controller: App\Controller\MessageController::upload
    methods: POST

messages_delete_selected:
    path: /messages/selected
    controller: App\Controller\MessageController::deleteSelected
    methods: DELETE

messages_delete_all:
    path: /messages/all
    controller: App\Controller\MessageController::deleteAll
    methods: DELETE

# Gpt Options
gpt_request_option_save:
    path: /gpt/request/option/save
    controller: App\Controller\GptRequestOptionController::save
    methods: POST

gpt_assistant_option_save:
    path: /gpt/assistant/option/save
    controller: App\Controller\GptAssistantOptionController::save
    methods: POST

gpt_search_option_save:
    path: /gpt/search/option/save
    controller: App\Controller\GptSearchOptionController::save
    methods: POST

gpt_summarize_option_save:
    path: /gpt/summarize/option/save
    controller: App\Controller\GptSummarizeOptionController::save
    methods: POST

# Knowledgebase Categories & Sections
knowledgebase_categories:
    path: /knowledgebase/categories
    controller: App\Controller\KnowledgebaseCategoryController::index
    methods: GET|HEAD

knowledgebase_sections:
    path: /knowledgebase/sections
    controller: App\Controller\KnowledgebaseSectionController::index
    methods: GET|HEAD

# Cloudflare Indexes
cloudflare_indexes:
    path: /cloudflare/indexes
    controller: App\Controller\CloudflareIndexController::index
    methods: GET|HEAD

cloudflare_index_store:
    path: /cloudflare/index
    controller: App\Controller\CloudflareIndexController::store
    methods: POST

cloudflare_index_delete:
    path: /cloudflare/index/{index}
    controller: App\Controller\CloudflareIndexController::delete
    methods: DELETE

cloudflare_vectors:
    path: /cloudflare/vectors
    controller: App\Controller\CloudflareVectorController::index
    methods: GET|HEAD

#cloudflare_vector_delete:
#    path: /cloudflare/index/{index}
#    controller: App\Controller\CloudflareIndexController::delete
#    methods: DELETE

# Misc
test_message:
    path: /test/message
    controller: App\Controller\TestController::testMessage

test_cloudflare_embedding_store:
    path: /test/cloudflare/embedding/store
    controller: App\Controller\TestController::testCloudflareEmbeddingStore
    methods: POST

test_cloudflare_embedding_search:
    path: /test/cloudflare/embedding/search
    controller: App\Controller\TestController::testCloudflareEmbeddingSearch
    methods: POST
